version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    env_file: .env
  db:
    image: mongo
    restart: always
    env_file: .env
